version: '3.8'
services:
  db:
    image: postgres:13
    container_name: crawl_db
    environment:
      POSTGRES_DB: crawl_data
      POSTGRES_USER: crawl_user
      POSTGRES_PASSWORD: crawl_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata: